### ISSUE TITLE
doc: dispatch directive fails in ReadTheDocws

### ISSUE THREAD

**Issue by ankostis** [vinci1it2000/schedula#5]
Schedula's directive for workflow diagrams breaks site generation, ass seen in this [co2mpas build]( https://readthedocs.org/projects/co2mpas-ta/builds/5142091/), and produces a WARNING as shown at the bottom.

```
reading sources... [ 98%] changes
reading sources... [ 98%] co2mpas_RelNotes
reading sources... [ 99%] developers
reading sources... [ 99%] explanation
failed at node 11294[1]
dot: maze.c:315: chkSgraph: Assertion `np->cells[1]' failed.
/usr/lib/python3/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/usr/lib/python3/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/sphinx/environment.py", line 569, in update
    self._read_serial(docnames, app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/sphinx/environment.py", line 589, in _read_serial
    self.read_doc(docname, app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/sphinx/environment.py", line 742, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/sphinx/io.py", line 49, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2320, in explicit_markup
    self.explicit_list(blank_finish)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2350, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 318, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2623, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 1614, in run
    documenter.generate(more_content=self.content)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 961, in generate
    self.add_content(more_content)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/schedula/ext/dispatcher.py", line 393, in add_content
    _plot(lines, dsp, dot_view_opt, self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/schedula/ext/dispatcher.py", line 152, in _plot
    dot.sitemap.render(directory=dspdir, index=False)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/schedula/utils/drw/__init__.py", line 1065, in render
    cached_view(node, directory, context, rendered, header)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/schedula/utils/drw/__init__.py", line 1090, in cached_view
    context=context, header=header
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/schedula/utils/drw/__init__.py", line 755, in view
    os.rename(fpath, filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/checkouts/latest/doc/_build/_dispatchers/dispatcher-fcc114a407f2bc5d83ebb5e51397ffe5838ff37a/predict_wltp_l.html/tmpvnu7nq5b.svg' -> '/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/checkouts/latest/doc/_build/_dispatchers/dispatcher-fcc114a407f2bc5d83ebb5e51397ffe5838ff37a/predict_wltp_l.html/engine_model-0.html'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/schedula/utils/drw/__init__.py", line 755, in view
    os.rename(fpath, filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/checkouts/latest/doc/_build/_dispatchers/dispatcher-fcc114a407f2bc5d83ebb5e51397ffe5838ff37a/predict_wltp_l.html/tmpvnu7nq5b.svg' -> '/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/checkouts/latest/doc/_build/_dispatchers/dispatcher-fcc114a407f2bc5d83ebb5e51397ffe5838ff37a/predict_wltp_l.html/engine_model-0.html'
The full traceback has been saved in /tmp/sphinx-err-rcpz42zi.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Command time: 121s Return: 1
```

NOTE that this build also reports this WARNING at the top:
```
...
[autosummary] generating autosummary for: AUTHORS.rst, changes.rst, co2mpas_RelNotes.rst, developers.rst, explanation.rst, glossary.rst, index.rst, install.rst, reference.rst, usage.rst
One of `xlrd`, `...` libraries is needed, will crash later!
Failed LOADING plugin(EntryPoint.parse('pandas_filters = pandalone.xleash._pandas_filters:load_as_xleash_plugin [pandas]')@pandalone 0.2.3) due to: No module named 'pandas.api'
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/pandalone/xleash/__init__.py", line 940, in _init_plugins
    plugin_loader = ep.load()
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/pandalone/xleash/_pandas_filters.py", line 21, in <module>
    import pandas.api.types as pdtypes
ImportError: No module named 'pandas.api'
Failed LOADING plugin(EntryPoint.parse('xlrd_be = pandalone.xleash.io._xlrd:load_as_xleash_plugin [xlrd]')@pandalone 0.2.3) due to: No module named 'xlrd'
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/pandalone/xleash/__init__.py", line 940, in _init_plugins
    plugin_loader = ep.load()
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/docs/checkouts/readthedocs.org/user_builds/co2mpas-ta/envs/latest/lib/python3.5/site-packages/pandalone/xleash/io/_xlrd.py", line 21, in <module>
    from xlrd import (xldate, XL_CELL_DATE, XL_CELL_EMPTY, XL_CELL_TEXT,
ImportError: No module named 'xlrd'
[autosummary] generating autosummary for: 
...
```

**Comment by ankostis** [comment]
Reported as URGENT & CRITICAL in JRCSTU/co2mpas#353.

**Comment by ankostis** [comment]
ping?

**Comment by ankostis** [comment]
@vinci1it2000 please do a release ASAP.
I always try to release ASAP when you discover bugs in my libraries.

**Comment by vinci1it2000** [comment]
Done with release 0.1.10

**Comment by ankostis** [comment]
But ~it~ co2mpas site still fails :-(
https://readthedocs.org/projects/co2mpas-ta/builds/5331145/

**Comment by vinci1it2000** [comment]
the problem is the svg logo of co2mpas.

**Comment by ankostis** [comment]
(haha, I didn't expect to read something like this :-)

Anyhow, we never had problem with the logos so far in our projects,
do you mind to explain what exactlty is the problem?

**Comment by vinci1it2000** [comment]
I'm moving the conversation in co2mpas issue JRCSTU/co2mpas#353.

**Comment by ankostis** [comment]
Will you put the issue link here?
